version: "3.3"

services:

  ws_webstudio:
    container_name: ws-core
    image: 'geomods/geomods-webstudio:${CAMUNDA_PLATFORM_VERSION:-1.0.2}'
    environment:
      webstudio_enableUserDB: false

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ws_store:/store-local

volumes:
  ws_store:
    external: false